#file: noinspection UndefinedAction,UndefinedParamsPresent
name: Python Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install python dependencies
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --cov=src tests/
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Generate coverage report
        run: |
          python -m coverage report
          python -m coverage xml
          python -m coverage html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/
          retention-days: 7

      - name: Upload XML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 7